name: Release TestPyPI

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Publish with Poetry to TestPyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish --build -n -r test-pypi -u __token__ -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
