name: Release TestPyPI

#
# Build and release package to TestPyPI using Poetry.
#
# - Can be used safely on all branches (even PRs).
# - Will fail if the the version is already available on TestPyPI.
#

on:
  workflow_dispatch:

jobs:
  primary:
    name: Primary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Handle cached Poetry
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Configure Poetry repo for TestPyPI
        run: poetry config repositories.test-pypi https://test.pypi.org/legacy/

      - name: Publish to TestPyPI with Poetry
        run: poetry publish --build -n -r test-pypi -u __token__ -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
