name: Tests and Checks

#
# Primary workflow for various tests and checks.
#

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [trunk]

jobs:
  primary:
    name: Primary
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.7"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ------------------------------------------------------------------------
      # Python & Poetry.

      - id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Handle cached Poetry
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ matrix.python-version }}-0

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Handle cached venv
        id: handle-cached-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-0

      - name: Install dependencies with Poetry
        if: steps.handle-cached-venv.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      # ------------------------------------------------------------------------
      # Tests.

      - name: Run tests with Pytest
        run: poetry run pytest --cov=src/testbench_tuna --cov-report=term-missing:skip-covered tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      # ------------------------------------------------------------------------
      # Pre-commit.

      - name: Pre-commit Cache
        if: strategy.job-index == 0
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.python-version }}

      - name: Pre-commit Setup
        if: strategy.job-index == 0
        run: poetry run pre-commit install

      - name: Pre-commit
        if: strategy.job-index == 0
        run: poetry run pre-commit run -v --show-diff-on-failure
